GET   http://localhost:5000/
Accept: application/json

###

POST http://localhost:5000/signUp
content-type: application/json

{
    "name" : "Ronit",
    "email" : "@gmail.com",
    "password" : ""
}

###

POST http://localhost:5000/signIn
Content-Type: application/json

{
    "email" : "@gmail.com",
    "password" : ""
}

###
POST http://localhost:5000/createpost
Content-Type: application/json
Authorization: Bearer 

{
    "title": "",
    "body": ""
}

###
POST http://localhost:5000/protected
Content-Type: application/json
Authorization: Bearer 