GET   http://localhost:5000/
Accept: application/json

###

POST http://localhost:5000/signUp
content-type: application/json

{
    "name" : "mikku",
    "email" : "mikku@gmail.com",
    "password" : "mikku"
}

###

POST http://localhost:5000/signIn
Content-Type: application/json

{
    "email" : "mikku@gmail.com",
    "password" : "mikku"
}

###
POST http://localhost:5000/createpost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDFiZjQ0N2NiMjk4MzAxYjBkMjRmZTciLCJpYXQiOjE2MTI0NDUwNjV9.7kFJu3M2dSVM6YIaOxO3hedkP5bXe8wHpnxCP7axm0g

{
    "title": "naya pic",
    "body": "10 rupaya ka pepsi tera bhai sexy"
}

###
POST http://localhost:5000/protected
Content-Type: application/json
Authorization: Bearer 

###
GET http://localhost:5000/allposts
Accept: application/json
###
GET http://localhost:5000/myposts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDFiZjQ0N2NiMjk4MzAxYjBkMjRmZTciLCJpYXQiOjE2MTI0NDUwNjV9.7kFJu3M2dSVM6YIaOxO3hedkP5bXe8wHpnxCP7axm0g
Accept: application/json