GET   http://localhost:5000/
Accept: application/json

###

POST http://localhost:5000/signUp
content-type: application/json

{
    "name" : "Sujaleshwar",
    "email" : "sujalchuhadhai@gmail.com",
    "password" : "chuhad"
}

###

POST http://localhost:5000/signIn
Content-Type: application/json

{
    "email" : "newUser@gmail.com",
    "password" : "ronit"
}

###
POST http://localhost:5000/protected
Content-Type: application/json
Authorization: Bearer .eyJfaWQiOiI1ZjdjM2Q3NjFiYThmNTFjMjBhZThlMGYiLCJpYXQiOjE2MDIyMzQ4MDB9.ixE85WEDYb81N4rsDHcMIdExOu8tLO