GET   http://localhost:5000/
Accept: application/json

###

POST http://localhost:5000/signUp
content-type: application/json

{
    "name" : "Sujaleshwar",
    "email" : "sujalchuhadhai@gmail.com",
    "password" : "chuhad"
}

###

POST http://localhost:5000/signIn
Content-Type: application/json

{
    "email" : "newUser@gmail.com",
    "password" : "ronit"
}

###
POST http://localhost:5000/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjdjM2Q3NjFiYThmNTFjMjBhZThlMGYiLCJpYXQiOjE2MDI4NjY1OTB9.PWShPfoTr-fEuNOovPSwMFVJ8AFM5pGbf79VzBEcoAI